### ISSUE TITLE
why is so slow 

### ISSUE THREAD

**Issue by r0x5r** [rook1337/googlecertfarm#1]
i use on forutune company it take 3 days to more days to complete this please increase

**Comment by rook1337** [comment]
Hello @rohit0x5 
It depends on the company if it is big then it might have many domains, so it is going to take time. If you have a solution, you can contribute to this.

**Comment by r0x5r** [comment]
and one issue is this toll give lots of duplicate domian

**Comment by r0x5r** [comment]
if i stop in middle so this not use dup tool

**Comment by rook1337** [comment]
Yes, if you stop this in middle you will get duplicate result because it removes duplicates at the end
